AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'
AWS_REGION: 'ap-northeast-1'
SECRET_KEY_BASE: '{{ webapp_secret_key_base }}'
DATABASE_URL: '{{ database_url }}'
REDIS_URL: '{{ redis_url }}'
JWT_SECRET: '{{ webapp_jwt_secret }}'
