---

- name: Fetch project
  git: repo={{ video_processor_repository }} accept_hostkey=yes dest={{ video_processor_project_dir }} key_file={{ video_processor_keyfile }}
  become: yes
  become_user: "{{ username }}"
  register: video_processor_git_fetch

- name: Install project dependencies
  pip: requirements={{ video_processor_project_dir }}/requirements.txt virtualenv="{{ video_processor_virtualenv }}"
  become: yes
  become_user: "{{ username }}"

- name: Install opencv2
  command: "cp {{ opencv_python_path }} {{ video_processor_virtualenv }}/lib/python{{ python_short_version }}/site-packages"
  args:
    creates: "{{ video_processor_virtualenv }}/lib/python{{ python_short_version }}/site-packages/{{ opencv_python_so }}"
  become: yes
  become_user: "{{ username }}"

- name: Add env file
  template: src=env dest={{ video_processor_project_dir }}/.env owner={{ username }} group={{ username }}

- name: Install project
  command: "{{ video_processor_python }} setup.py install"
  args:
    chdir: "{{ video_processor_project_dir }}"
  when: video_processor_git_fetch | changed and env != 'dev'
  become: yes
  become_user: "{{ username }}"

- name: Setup project for dev
  command: "{{ video_processor_python }} setup.py develop"
  args:
    chdir: "{{ video_processor_project_dir }}"
  when: video_processor_git_fetch | changed and env == 'dev'
  become: yes
  become_user: "{{ username }}"
