---

mysql_packages:
  - mariadb-client
  - mariadb-server

mysql_databases:
  - name: videalize_production

mysql_users:
  - name: videalize
    host: "%"
    password: "{{ mysql_videalize_password }}"
    priv: "videalize_production.*:ALL"
