---

video_processor_repository: git@github.com:videalize/video-processor.git
video_processor_project_dir: "{{ user_home }}/videalize-video-processor"
video_processor_keyfile: "{{ user_home }}/.ssh/video_processor_deploy"

video_processor_env:
  VIDEALIZE_ENV: "{{ env }}"
  REDIS_URL: "{{ redis_url }}"
  AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
